### ISSUE TITLE
Is the marquee displayed on main monitor 1?

### ISSUE THREAD

**Issue by Chan76** [Nelfe80/RetroBat-Marquee-Manager#2]
The main monitor is number 1 and the marquee monitor is number 2.
I modified the events.ini file and set number 2 in the monitor settings, but a marquee is displayed on monitor number 1. Can you tell me why?

**Comment by Nelfe80** [comment]
The Windows monitor number is not the one used by MPV, which is an independent program with its own logic for targeting monitors. I advise you to test with 0 or 1 or 2.
