### ISSUE TITLE
Add marquees

### ISSUE THREAD

**Issue by manni-ctb** [Nelfe80/RetroBat-Marquee-Manager#3]
For some systems the marquees are not recognized and any attempt to add them manually failed in my case (e.g. snes marquees). Does it have to do with the config file, or are there any other reasons to this?

**Comment by Nelfe80** [comment]
What is your RetroBat version and theme ? Please share me your config.ini and activate debug and share me your log file.. Thanks.

**Comment by manni-ctb** [comment]
Here is the config.ini and the scrapfail file (I hope it is the one you
need...).
I have the Retrobat version 6.1.0-stable-win64, the theme I am using is
"es-theme-lamf-hypermax-plus+v8". Everything runs fine, but for some
systems most of the marquees cannot be installed.

Thanks for your help

Am Mi., 24. Apr. 2024 um 12:04 Uhr schrieb Nelfe80 ***@***.***

**Comment by Nelfe80** [comment]
This theme is not officially supported by RetroBat. This may explain the problems.
It's the log file when you set debug = true in the config.ini file that I need.

**Comment by manni-ctb** [comment]
I set the theme to "carbon master" resulting in the same state as with the other theme. And I set "MarqueeAutoScrapingDebug = true" but I cannot find any log file in the marquee manager folder... Do I have to look for it somewhere else?

Thanks for your patience and support.
________________________________
Von: Nelfe80 ***@***.***>
Gesendet: Donnerstag, 25. April 2024 08:37
An: Nelfe80/RetroBat-Marquee-Manager ***@***.***>
Cc: manni-ctb ***@***.***>; Author ***@***.***>
Betreff: Re: [Nelfe80/RetroBat-Marquee-Manager] Add marquees (Issue #3)


This theme is not officially supported by RetroBat. This may explain the problems.
It's the log file when you set debug = true in the config.ini file that I need.

**Comment by manni-ctb** [comment]
Hi Norman. Did you have time to have a look at my config file? I still don't get what I am missing to add or adjust the right settings to get all the game logos for the different systems in the marquee manager. Kind regards Manni Sent from my phone-------- Original message --------From: Nelfe80 ***@***.***>Date: Thu, Apr 25, 2024, 08:37To: Nelfe80/RetroBat-Marquee-Manager ***@***.***>Cc: manni-ctb ***@***.***>, Author ***@***.***>Subject: Re: [Nelfe80/RetroBat-Marquee-Manager] Add marquees (Issue #3)
This theme is not officially supported by RetroBat. This may explain the problems.
It's the log file when you set debug = true in the config.ini file that I need.

**Comment by Nelfe80** [comment]
Hi, in the config file, there is a "debug = true". Please check this. It's not MarqueeAutoScrapingDebug = true.
Please send me the debug file. Best regards.

**Comment by manni-ctb** [comment]
Sorry to bother you again. But I just can't find any option to change debug=true in the config file. Shall I delete the whole "MarqueeManager"-folder and try to reinstall it over again? I don't see any other option at the moment... Sent from my phone-------- Original message --------From: Nelfe80 ***@***.***>Date: Sat, Apr 27, 2024, 11:58To: Nelfe80/RetroBat-Marquee-Manager ***@***.***>Cc: manni-ctb ***@***.***>, Author ***@***.***>Subject: Re: [Nelfe80/RetroBat-Marquee-Manager] Add marquees (Issue #3)
Hi, in the config file, there is a "debug = true". Please check this. It's not MarqueeAutoScrapingDebug = true.
Please send me the debug file. Best regards.

**Comment by Nelfe80** [comment]
I'm really sorry, I made a mistake. I confused it with another application. It's logfile=true.

**Comment by manni-ctb** [comment]
No problem, don't worry. I downloaded the actual marquee manager folder again, deleted the existing one and reinstalled. Appearently it seems to work now (at least for the snes-system, which did not work at all lately). Unfortunately I deleted all my marquees (I was so desperate), so I am not sure if it works for all the systems. But if you don't mind I can update you with infos once I got all the marquees again together. Thanks for your support! Sent from my phone-------- Original message --------From: Nelfe80 ***@***.***>Date: Sat, Apr 27, 2024, 19:37To: Nelfe80/RetroBat-Marquee-Manager ***@***.***>Cc: manni-ctb ***@***.***>, Author ***@***.***>Subject: Re: [Nelfe80/RetroBat-Marquee-Manager] Add marquees (Issue #3)
I'm really sorry, I made a mistake. I confused it with another application. It's logfile=true.

**Comment by Nelfe80** [comment]
No problem, i'm ready.

**Comment by manni-ctb** [comment]
Hi Norman. Just to tell you that everything works with the marquee manager. I also set up retroachievement which runs fine as well. I guess I downloaded two versions of the manager and missed up the folders. Thanks for your work! Greetings Sent from my phone-------- Original message --------From: Nelfe80 ***@***.***>Date: Sat, Apr 27, 2024, 20:09To: Nelfe80/RetroBat-Marquee-Manager ***@***.***>Cc: manni-ctb ***@***.***>, Author ***@***.***>Subject: Re: [Nelfe80/RetroBat-Marquee-Manager] Add marquees (Issue #3)
No problem, i'm ready.

**Comment by Nelfe80** [comment]
Perfect, thank you for this good news 👍
